version: 1.0.{build}
build_script:
- cmd: >-
    npm i

    npm audit fix

    npm run build

artifacts:
 - path: '\dist\learnwithmentor-web'
   name: WebDeployPackage
   type: WebDeployPackage

deploy:
  - provider: Environment
    name: production-web
    on:
      branch: master 
  